name: medcall_pro
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  lottie: ^3.3.0
  iconsax: ^0.0.8
  flutter_svg: ^2.0.16
  flutter_multi_formatter: ^2.13.0
  shared_preferences: ^2.3.5
  table_calendar: ^3.1.3
  intl: ^0.19.0
  timeline_tile: ^2.0.0
  google_fonts: ^6.2.1
  fl_chart: ^0.70.1
  glassmorphism: ^3.0.0
  flutter_slidable: ^3.1.2
  url_launcher: ^6.3.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  ios: true

  image_path: "assets/logo.png"

flutter:
  assets:
    - assets/
    - assets/lottie/

  uses-material-design: true